#!/bin/sh
set -e

echo "TeXing documentation"
# TeX the manual and build its bibliography
tex manual
bibtex manual
# TeX the manual again to incorporate the ToC ... and build the index
tex manual 
tex manual
../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual

# Create PDF version
pdftex manual; pdftex manual 

# Create the HTML version of the manual (uncomment next 3 lines, if needed)
rm -rf ../htm
mkdir ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -i -u -c -n ParGAP . ../htm

##########################################################################
##
#E
